from economy import Economy

economy = Economy(
    id="MILD_MILD_WEST",
    numeric_id=6,
    # as of May 2015 the following cargos must have fixed positions if used by an economy:
    # passengers: 0, mail: 2, goods 5, food 11
    # keep the rest of the cargos alphabetised
    # bump the min. compatible version if this list changes
    cargos=[
        "passengers",
        "acetic_acid",
        "mail",
        "alcohol",
        "ammonia",
        "apples",
        "carbon_dioxide",
        "cement",
        "cleaning_agents",
        "coal",
        "coke",
        "food",
        "engineering_supplies",
        "food_additives",
        "explosives",
        "farm_supplies",
        "fertiliser",
        "fish",
        "grain",
        "iron_ore",
        "kaolin",
        "limestone",
        "livestock",
        "logs",
        "lumber",
        "lye",
        "milk",
        "methanol",
        "molasses",
        "naphtha",
        "oil",
        "paints_and_coatings",
        "paper",
        "petrol",
        "phosphate",
        "phosphoric_acid",
        "plastics",
        "potash",
        "quicklime",
        "salt",
        "scrap_metal",
        "slag",
        "steel_sections",
        "steel_sheet",
        "steel_wire_rod",
        "sulphuric_acid",
        "tin",
        "tinplate",
        "vegetables",
        "vehicles",
        "yeast",
        "zinc",
        "zinc_ore",
    ],
    cargoflow_graph_tuning={
        "group_edges_subgraphs": [],
        "ranking_subgraphs": [
            # ("same", ["port", "goods"]),
            # ("sink", ["T_town_industries", "N_force_rank"]),
        ],
        "clusters": [
            # {"nodes": [], "rank": "", "color": ""},
        ],
    },
)
